version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: cryptoData
      MYSQL_USER: testUser
      MYSQL_PASSWORD: haslo123
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  client:
    container_name: client
    build:
      context: ./frontend
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "5173:80"

  server:
    container_name: server
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cryptoData
      SPRING_DATASOURCE_USERNAME: testUser
      SPRING_DATASOURCE_PASSWORD: haslo123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
